### ISSUE TITLE
CRAN submission?

### ISSUE THREAD

**Issue by llrs** [dalejbarr/explan#1]
Nice article and package.
Do you have plans to have the package at CRAN?

Related to this, CRAN accepts many licenses, specially those at [their list](https://cran.r-project.org/web/licenses/), but the CC-BY is not recommended as a software license, maybe the closest is GPLv3
Looking forward to use the package

**Comment by dalejbarr** [comment]
Hi there, thanks for the feedback!

We will probably submit to CRAN in the coming weeks, after we do some final debugging and testing. At that point we'll consider the possibility of changing the license.
